// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/assets/video.gif"
    | "/background.js"
    | "/content-scripts/course.js"
    | "/content-scripts/file.js"
    | "/content-scripts/video.js"
    | "/course-selector.css"
    | "/file-download.css"
    | "/icons/icon.svg"
    | "/icons/icon128.png"
    | "/icons/icon16.png"
    | "/icons/icon32.png"
    | "/icons/icon48.png"
    | "/popup.html"
    | "/rules.json"
    | "/video-download.css"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
